slam_toolbox:
  ros__parameters:
    # === SOLVER PARAMETERS ===
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # === ODOM PARAMETERS ===
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_map_saver: true
    mode: mapping

    # === LIDAR PARAMETERS (A1M8 Specific) ===
    # A1M8 specifications: 15cm - 12m range, 0.5° resolution
    min_laser_range: 0.20  # Increased from 0.15 to match A1M8's actual minimum (warning showed 0.2m)
    max_laser_range: 12.0
    
    # === PROCESSING PARAMETERS ===
    # Reduce processing frequency to handle queue overflow
    map_update_interval: 2.0  # Increased from 5.0 to reduce processing load
    scan_buffer_size: 20      # Increased buffer size to handle more scans
    scan_buffer_maximum_scan_distance: 12.0
    
    # === QUEUE PARAMETERS ===
    # Increase queue sizes to prevent message dropping
    tf_buffer_duration: 10.0  # Increased from 30.0 to reduce memory usage but keep sync
    transform_timeout: 0.5    # Increased timeout for transform lookups
    
    # === MOTION MODEL PARAMETERS ===
    # Reduce sensitivity to handle high-frequency data
    minimum_travel_distance: 0.2  # Increased from 0.5 to reduce processing
    minimum_travel_heading: 0.3   # Increased from 0.5 to reduce processing
    scan_matching_minimum_travel_distance: 0.2
    scan_matching_minimum_travel_heading: 0.3

    # === LOOP CLOSURE PARAMETERS ===
    # Reduce loop closure frequency to improve performance
    loop_search_maximum_distance: 4.0  # Reduced from 3.0
    loop_match_minimum_chain_size: 15   # Increased from 10 for better stability
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # === CORRELATION PARAMETERS ===
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # === SCAN MATCHER PARAMETERS ===
    # Adjust for better performance with high-frequency data
    coarse_search_angle_offset: 0.349
    fine_search_angle_offset: 0.00349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    
    # === ADDITIONAL PERFORMANCE PARAMETERS ===
    # General settings for stability
    debug_logging: false
    throttle_scans: 2           # Process every 2nd scan to reduce load
    transform_publish_period: 0.1  # 10Hz transform publishing
    resolution: 0.05            # Map resolution in meters
    minimum_time_interval: 0.15  # Minimum time between scans (matches bridge frequency)
    stack_size_to_use: 40000000 # Larger stack for complex maps
    enable_interactive_mode: true
    
    # === SCAN PROCESSING PARAMETERS ===
    use_scan_matching: true
    use_scan_barycenter: true
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 2.0
    do_loop_closing: true
    
    # === ADDITIONAL CORRELATION PARAMETERS ===
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    
    # === SCAN MATCHER PENALTIES ===
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0 