<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bcr_bot">

    <!--................................ XACRO CONSTANTS .............................. -->

    <!-- Robot dimensions - directly scaled down to 50% size -->
    <xacro:property name="chassis_mass" value="2.5"/>
    <xacro:property name="chassis_length" value="0.5"/>
    <xacro:property name="chassis_width" value="0.5"/>
    <xacro:property name="chassis_height" value="0.25"/>

    <xacro:property name="traction_wheel_mass" value="0.125"/>
    <xacro:property name="traction_wheel_base" value="0.44"/>
    <xacro:property name="traction_max_wheel_torque" value="5000"/>
    <xacro:property name="traction_wheel_friction" value="5.0"/>

    <xacro:property name="trolley_wheel_mass" value="0.0125"/>
    <xacro:property name="trolley_track_width" value="0.27"/>
    <xacro:property name="trolley_wheel_friction" value="0.0"/>
    <xacro:property name="trolley_wheel_radius" value="0.03"/>
    <!-- a small constant -->
    <xacro:property name="eps" value="0.001"/>

    <xacro:property name="traction_wheel_radius" value="0.03"/>
    <xacro:property name="traction_wheel_width" value="0.025"/>
    <xacro:property name="traction_track_width" value="0.3"/>

    <xacro:property name="two_d_lidar_update_rate" value="30"/>
    <xacro:property name="two_d_lidar_sample_size" value="361"/>
    <xacro:property name="two_d_lidar_min_angle" value="0"/>
    <xacro:property name="two_d_lidar_max_angle" value="360"/>
    <xacro:property name="two_d_lidar_min_range" value="0.275"/>
    <xacro:property name="two_d_lidar_max_range" value="8"/>

    <xacro:property name="camera_baseline" value="0.03"/>
    <xacro:property name="camera_height" value="0.05"/>
    <xacro:property name="camera_horizontal_fov" value="60"/>

    <xacro:arg name="robot_namespace" default=""/>
    <xacro:arg name="wheel_odom_topic" default="odom" />
    <xacro:arg name="camera_enabled" default="false" />
    <xacro:arg name="stereo_camera_enabled" default="false" />
    <xacro:arg name="two_d_lidar_enabled" default="false" />
    <xacro:arg name="publish_wheel_odom_tf" default="true" />
    <xacro:arg name="conveyor_enabled" default="false"/>
    <xacro:arg name="ground_truth_frame" default="map"/>
    <xacro:arg name="sim_gazebo" default="false" />
    <xacro:arg name="sim_ign" default="false" />
    <xacro:arg name="sim_gz" default="false" />
    <xacro:arg name="odometry_source" default="world" />

    <xacro:property name="odometry_source" value="$(arg odometry_source)"/>

    <!-- ............................... LOAD MACROS ................................. -->

    <xacro:include filename="$(find bcr_bot)/urdf/materials.xacro"/>
    <xacro:include filename="$(find bcr_bot)/urdf/macros.xacro"/>

    <xacro:if value="$(arg sim_gazebo)">
        <xacro:include filename="$(find bcr_bot)/urdf/gazebo.xacro"/>
    </xacro:if>

    <xacro:if value="$(arg sim_ign)">
        <xacro:include filename="$(find bcr_bot)/urdf/ign.xacro"/>
    </xacro:if>

    <xacro:if value="$(arg sim_gz)">
        <xacro:include filename="$(find bcr_bot)/urdf/gz.xacro"/>
    </xacro:if>

    <!-- ................................ BASE LINK .................................. -->
    <link name="base_footprint"/>

    <link name="base_link"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.10" rpy="0 0 0.0" />
    </joint>

    <link name="chassis_link">

        <collision>
            <origin xyz="0 0 0.125" rpy="0 0 0" />
            <geometry>
                <box size="0.5 0.5 0.25"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0.125" rpy="0 0 0" />
            <geometry>
                <box size="0.5 0.5 0.25"/>
            </geometry>
            <material name="red_orange">
                <color rgba="1 0.302 0 1"/>
            </material>
        </visual>

        <inertial>
            <mass value="2.5" />
            <xacro:box_inertia m="2.5" x="0.5" y="0.5" z="0.25"/>
        </inertial>

    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0.0 0 0" rpy="0 0 0.0" />
    </joint>

    <!-- Front marker -->
    <link name="front_marker">
        <visual>
            <origin xyz="-0.25 0 0.125" rpy="0 0 0"/>
            <geometry><box size="0.025 0.025 0.025"/></geometry>
            <material name="red"><color rgba="1 0 0 1"/></material>
        </visual>
    </link>
    <joint name="front_marker_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="front_marker"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Dummy wheels for visual appearance (like sperro) -->
    <!-- Front Left Wheel -->
    <link name="fl_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.5708 0 0"/>
            <geometry><cylinder radius="0.03" length="0.025"/></geometry>
            <material name="black"><color rgba="0.2 0.2 0.2 1"/></material>
        </visual>
        <!-- No collision for dummy wheels to prevent physics interference -->
        <inertial>
            <mass value="0.00125"/>
            <inertia ixx="0.0000003" ixy="0" ixz="0" iyy="0.0000003" iyz="0" izz="0.0000003"/>
        </inertial>
    </link>
    <joint name="fl_wheel_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="fl_wheel"/>
        <origin xyz="-0.2 0.15 0.0" rpy="0 0 0"/>
    </joint>

    <!-- Front Right Wheel -->
    <link name="fr_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.5708 0 0"/>
            <geometry><cylinder radius="0.03" length="0.025"/></geometry>
            <material name="black"><color rgba="0.2 0.2 0.2 1"/></material>
        </visual>
        <!-- No collision for dummy wheels to prevent physics interference -->
        <inertial>
            <mass value="0.00125"/>
            <inertia ixx="0.0000003" ixy="0" ixz="0" iyy="0.0000003" iyz="0" izz="0.0000003"/>
        </inertial>
    </link>
    <joint name="fr_wheel_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="fr_wheel"/>
        <origin xyz="-0.2 -0.15 0.0" rpy="0 0 0"/>
    </joint>

    <!-- Rear Left Wheel -->
    <link name="rl_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.5708 0 0"/>
            <geometry><cylinder radius="0.03" length="0.025"/></geometry>
            <material name="black"><color rgba="0.2 0.2 0.2 1"/></material>
        </visual>
        <!-- No collision for dummy wheels to prevent physics interference -->
        <inertial>
            <mass value="0.00125"/>
            <inertia ixx="0.0000003" ixy="0" ixz="0" iyy="0.0000003" iyz="0" izz="0.0000003"/>
        </inertial>
    </link>
    <joint name="rl_wheel_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="rl_wheel"/>
        <origin xyz="0.2 0.15 0.0" rpy="0 0 0"/>
    </joint>

    <!-- Rear Right Wheel -->
    <link name="rr_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="1.5708 0 0"/>
            <geometry><cylinder radius="0.03" length="0.025"/></geometry>
            <material name="black"><color rgba="0.2 0.2 0.2 1"/></material>
        </visual>
        <!-- No collision for dummy wheels to prevent physics interference -->
        <inertial>
            <mass value="0.00125"/>
            <inertia ixx="0.0000003" ixy="0" ixz="0" iyy="0.0000003" iyz="0" izz="0.0000003"/>
        </inertial>
    </link>
    <joint name="rr_wheel_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="rr_wheel"/>
        <origin xyz="0.2 -0.15 0.0" rpy="0 0 0"/>
    </joint>

    <!-- ................................ WHEELS ..................................... -->

    <xacro:trolley_wheel cardinality="front" dexterity="left" origin_x="${chassis_length/2}" origin_y="${trolley_track_width/2}" origin_z="-${traction_wheel_radius}"/>
    <xacro:trolley_wheel cardinality="front" dexterity="right" origin_x="${chassis_length/2}" origin_y="-${trolley_track_width/2}" origin_z="-${traction_wheel_radius}"/>

    <xacro:trolley_wheel cardinality="back" dexterity="left" origin_x="-${chassis_length/2}" origin_y="${trolley_track_width/2}" origin_z="-${traction_wheel_radius}"/>
    <xacro:trolley_wheel cardinality="back" dexterity="right" origin_x="-${chassis_length/2}" origin_y="-${trolley_track_width/2}" origin_z="-${traction_wheel_radius}"/>

    <xacro:traction_wheel cardinality="middle" dexterity="left" origin_x="0" origin_y="${traction_track_width/2}" origin_z="-${traction_wheel_radius}"/>
    <xacro:traction_wheel cardinality="middle" dexterity="right" origin_x="0" origin_y="-${traction_track_width/2}" origin_z="-${traction_wheel_radius}"/>

    <!-- ............................. 2D LIDAR ........................................ -->

    <xacro:if value="$(arg two_d_lidar_enabled)">

        <link name="two_d_lidar">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <cylinder length="0.03" radius="0.0375"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <cylinder length="0.03" radius="0.0375"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.0125"/>
            <inertia ixx="0.0000003" ixy="0" ixz="0" iyy="0.0000003" iyz="0" izz="0.0000003"/>
            </inertial>
        </link>

        <joint name="two_d_lidar_joint" type="fixed">
            <parent link="base_link"/>
            <child link="two_d_lidar"/>
        <origin xyz="0.175 0 0.27" rpy="0 0 0" />
        </joint>

        <gazebo reference="two_d_lidar">
            <material>Gazebo/White</material>
        </gazebo>

    </xacro:if>

    <!-- ............................. IMU ........................................ -->

    <link name="imu_frame">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="0.02" radius="0.02"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="0.02" radius="0.02"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.00625"/>
            <inertia ixx="0.0000001" ixy="0" ixz="0" iyy="0.0000001" iyz="0" izz="0.0000001"/>
        </inertial>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_frame"/>
        <origin xyz="0.125 0 0.27" rpy="0 0 0"/>
    </joint>

    <!-- ............................. CAMERA ........................................ -->

    <xacro:if value="$(arg camera_enabled)">

        <!-- KINECT CAMERA -->

        <link name="kinect_camera">

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.035 0.15 0.045"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find bcr_bot)/meshes/kinect/d415.dae" scale="0.5 0.5 0.5"/>
                </geometry>
                <material name="black"/>
            </visual>

            <inertial>
                <mass value="0.00125"/>
                <xacro:box_inertia m="0.00125" x="0.035" y="0.15" z="0.045"/>
            </inertial>

        </link>

        <joint name="kinect_camera_joint" type="fixed">
            <origin rpy="0 0 0" xyz="${chassis_length/2} 0 ${chassis_height/7}"/>
            <parent link="base_link"/>
            <child link="kinect_camera"/>
        </joint>

        <link name="kinect_camera_optical"/>

        <joint name="kinect_camera_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
            <parent link="kinect_camera"/>
            <child link="kinect_camera_optical"/>
        </joint>

    </xacro:if>

    <!-- .............................STEREO CAMERA ........................................ -->

    <xacro:if value="$(arg stereo_camera_enabled)">

        <!-- STEREO CAMERA -->

        <link name="stereo_camera">

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.035 0.15 0.045"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find bcr_bot)/meshes/kinect/d415.dae" scale="0.5 0.5 0.5"/>
                </geometry>
                <material name="black"/>
            </visual>

            <inertial>
                <mass value="0.00125"/>
                <xacro:box_inertia m="0.00125" x="0.035" y="0.15" z="0.045"/>
            </inertial>

        </link>

        <joint name="stereo_camera_joint" type="fixed">
            <origin rpy="0 0 0" xyz="${chassis_length/2} 0 ${chassis_height/7}"/>
            <parent link="base_link"/>
            <child link="stereo_camera"/>
        </joint>

        <link name="stereo_camera_optical"/>

        <joint name="stereo_camera_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
            <parent link="stereo_camera"/>
            <child link="stereo_camera_optical"/>
        </joint>

    </xacro:if>

    <!-- ............................. ROOF ........................................ -->

    <link name="roof_link">

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.5 0.5 0.0075"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="0.125"/>
            <xacro:box_inertia m="0.125" x="0.5" y="0.3" z="0.0075"/>
        </inertial>

    </link>

    <joint name="roof_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="roof_link"/>
        <origin xyz="0 0 0.135" rpy="0 0 0" />
    </joint>

    <!-- ............................. CONVEYOR ........................................ -->

    <xacro:if value="$(arg conveyor_enabled)">

        <link name="conveyor_belt">

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.5 0.3 0.0075"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.5 0.3 0.0075"/>
                </geometry>
            </visual>

            <inertial>
                <mass value="0.125"/>
                <xacro:box_inertia m="0.125" x="0.5" y="0.3" z="0.0075"/>
            </inertial>

        </link>

        <joint name="conveyor_joint" type="fixed">
            <parent link="base_link"/>
            <child link="conveyor_belt"/>
            <origin xyz="0 0 0.26" rpy="0 0 0" />
        </joint>

    </xacro:if>
    <!-- ............................................................................... -->

</robot>